'_io.TextIOWrapper' object is not callable
WPe9xdL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nXe0vbx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
negJYdw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lejRRej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbkR5az
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelY5aK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmZOdY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
pen5Rd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xbo2jag
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepY2aM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqx2ap
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
YerkEaO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Vyb8mdv
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9av2maG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DdwpRe1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7axk9ey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
PdyP7bQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
kazpYdJ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9aADOev
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
6dBBXd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DbDkxal
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
oeERva0
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
RdG67bD
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QdJ62dO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
1aKrReQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
wdL9wej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
M7e5Ba2
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
1aM8AeW
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
0dNk6eL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
YaOYpdx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
ZdPNwaK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
qaQWldn
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
5xe7jd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
PdR6qdG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
5eVOMaE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
NbW6Jay
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
BeXDWey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QbYEKbz
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QeZ6Jep
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Qe1wRbJ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
rb2kKdW
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Le31Mb6
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Rb4x1bB
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7e5yBe2
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9b68neE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xe73je7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
yb82mev
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Pe9rxaL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Xe0Rvbx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
neg5Ybw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lej2Rej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbk55ez
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelO5dK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmwOeY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
penZRe7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xboYjeg
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepg2dM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqj2dp
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Yer0EbO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9avgmbG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DdwjRb1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
K9b6nbE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
neg56bw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lej25ej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbk5Xez
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelO6dK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmw0eY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
penZle7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xboYKeg
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepg6dM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqjrdp
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Yer06bO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9avgrbG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Ddwjwb1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7axGrey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Pdy8WbQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nXe0vbx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
WPe9xdL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
negJYdw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lejRRej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbkR5az
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelY5aK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmZOdY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
pen5Rd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xbo2jag
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepY2aM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqx2ap
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
YerkEaO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Vyb8mdv
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9av2maG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DdwpRe1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7axk9ey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
PdyP7bQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
kazpYdJ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9aADOev
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
6dBBXd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DbDkxal
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
oeERva0
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
RdG67bD
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QdJ62dO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
1aKrReQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
wdL9wej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
M7e5Ba2
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
1aM8AeW
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
0dNk6eL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
YaOYpdx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
ZdPNwaK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
qaQWldn
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
5xe7jd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
PdR6qdG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
5eVOMaE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
NbW6Jay
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
BeXDWey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QbYEKbz
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QeZ6Jep
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Qe1wRbJ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
rb2kKdW
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Le31Mb6
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Rb4x1bB
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7e5yBe2
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9b68neE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xe73je7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
yb82mev
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Pe9rxaL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Xe0Rvbx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
neg5Ybw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lej2Rej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbk55ez
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelO5dK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmwOeY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
penZRe7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xboYjeg
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepg2dM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqj2dp
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Yer0EbO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9avgmbG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DdwjRb1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
K9b6nbE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
neg56bw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lej25ej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbk5Xez
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelO6dK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmw0eY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
penZle7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xboYKeg
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepg6dM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqjrdp
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Yer06bO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9avgrbG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Ddwjwb1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7axGrey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Pdy8WbQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
negJYdw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
WPe9xdL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nXe0vbx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lejRRej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbkR5az
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelY5aK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmZOdY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
pen5Rd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xbo2jag
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepY2aM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqx2ap
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
YerkEaO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Vyb8mdv
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9av2maG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DdwpRe1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7axk9ey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
PdyP7bQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
kazpYdJ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9aADOev
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
6dBBXd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DbDkxal
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
oeERva0
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
RdG67bD
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QdJ62dO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
1aKrReQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
wdL9wej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
M7e5Ba2
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
1aM8AeW
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
0dNk6eL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
YaOYpdx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
ZdPNwaK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
qaQWldn
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
5xe7jd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
PdR6qdG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
5eVOMaE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
NbW6Jay
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
BeXDWey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QbYEKbz
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QeZ6Jep
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Qe1wRbJ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
rb2kKdW
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Le31Mb6
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Rb4x1bB
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7e5yBe2
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9b68neE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xe73je7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
yb82mev
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Pe9rxaL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Xe0Rvbx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
neg5Ybw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lej2Rej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbk55ez
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelO5dK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmwOeY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
penZRe7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xboYjeg
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepg2dM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqj2dp
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Yer0EbO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9avgmbG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DdwjRb1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
K9b6nbE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
neg56bw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lej25ej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbk5Xez
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelO6dK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmw0eY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
penZle7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xboYKeg
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepg6dM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqjrdp
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Yer06bO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9avgrbG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Ddwjwb1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7axGrey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Pdy8WbQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
WPe9xdL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
negJYdw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nXe0vbx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lejRRej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbkR5az
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelY5aK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmZOdY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
pen5Rd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xbo2jag
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepY2aM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqx2ap
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
YerkEaO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Vyb8mdv
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9av2maG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DdwpRe1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7axk9ey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
PdyP7bQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
kazpYdJ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9aADOev
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
6dBBXd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DbDkxal
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
oeERva0
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
RdG67bD
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QdJ62dO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
1aKrReQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
wdL9wej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
M7e5Ba2
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
1aM8AeW
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
0dNk6eL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
YaOYpdx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
ZdPNwaK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
qaQWldn
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
5xe7jd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
PdR6qdG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
5eVOMaE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
NbW6Jay
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
BeXDWey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QbYEKbz
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QeZ6Jep
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Qe1wRbJ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
rb2kKdW
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Le31Mb6
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Rb4x1bB
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7e5yBe2
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9b68neE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xe73je7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
yb82mev
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Pe9rxaL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Xe0Rvbx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
neg5Ybw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lej2Rej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbk55ez
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelO5dK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmwOeY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
penZRe7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xboYjeg
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepg2dM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqj2dp
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Yer0EbO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9avgmbG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DdwjRb1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
K9b6nbE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
neg56bw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lej25ej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbk5Xez
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelO6dK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmw0eY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
penZle7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xboYKeg
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepg6dM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqjrdp
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Yer06bO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9avgrbG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Ddwjwb1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7axGrey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Pdy8WbQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nXe0vbx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
negJYdw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
WPe9xdL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lejRRej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbkR5az
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelY5aK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmZOdY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
pen5Rd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xbo2jag
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepY2aM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqx2ap
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
YerkEaO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Vyb8mdv
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9av2maG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DdwpRe1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7axk9ey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
PdyP7bQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
kazpYdJ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9aADOev
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
6dBBXd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DbDkxal
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
oeERva0
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
RdG67bD
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QdJ62dO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
1aKrReQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
wdL9wej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
M7e5Ba2
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
1aM8AeW
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
0dNk6eL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
YaOYpdx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
ZdPNwaK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
qaQWldn
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
5xe7jd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
PdR6qdG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
5eVOMaE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
NbW6Jay
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
BeXDWey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QbYEKbz
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QeZ6Jep
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Qe1wRbJ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
rb2kKdW
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Le31Mb6
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Rb4x1bB
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7e5yBe2
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9b68neE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xe73je7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
yb82mev
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Pe9rxaL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Xe0Rvbx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
neg5Ybw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lej2Rej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbk55ez
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelO5dK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmwOeY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
penZRe7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xboYjeg
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepg2dM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqj2dp
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Yer0EbO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9avgmbG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DdwjRb1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
K9b6nbE
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
neg56bw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lej25ej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbk5Xez
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelO6dK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmw0eY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
penZle7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xboYKeg
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepg6dM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqjrdp
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Yer06bO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9avgrbG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Ddwjwb1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7axGrey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Pdy8WbQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
negJYdw
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nXe0vbx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
WPe9xdL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
lejRRej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mbkR5az
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
nelY5aK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
vbmZOdY
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
pen5Rd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
xbo2jag
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
mepY2aM
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
zbqx2ap
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
YerkEaO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
Vyb8mdv
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9av2maG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DdwpRe1
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
7axk9ey
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
PdyP7bQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
kazpYdJ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
9aADOev
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
6dBBXd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
DbDkxal
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
oeERva0
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
RdG67bD
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
QdJ62dO
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
1aKrReQ
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
wdL9wej
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
M7e5Ba2
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
1aM8AeW
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
0dNk6eL
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
YaOYpdx
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
ZdPNwaK
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
qaQWldn
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
5xe7jd7
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
'_io.TextIOWrapper' object is not callable
PdR6qdG
Traceback (most recent call last):
  File "plot.py", line 24, in readcontrast
    plotlog((date_time_obj1 - date_time_obj).total_seconds())
TypeError: '_io.TextIOWrapper' object is not callable
